# theme = "monokai_soda"
# theme = "monokai_pro_spectrum"
# theme = "gruvbox"
theme = "gruvbox_dark_hard"
# theme = "flexoki_dark"

[editor]
line-number = "relative"
cursorline = true
cursorcolumn = false
scrolloff = 4
text-width = 88
rulers = [88, 120]
bufferline = "multiple"
mouse = true
scroll-lines = 3
middle-click-paste = true
default-yank-register = "\""
continue-comments = true
auto-completion = true
path-completion = true
completion-trigger-len = 0
preview-completion-insert = false
completion-replace = false
auto-format = true
default-line-ending = "native"
insert-final-newline = true
trim-final-newlines = true
trim-trailing-whitespace = true
# jump-label-alphabet = "abcdefghijklmnopqrstuvwxyz1234567890"
color-modes = true
# Minimum severity to show a diagnostic after the end of a line:
end-of-line-diagnostics = "hint"
editor-config = true
soft-wrap.enable = true

[editor.smart-tab]
enable = false
supersede-menu = true

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 5000

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "all"

[editor.indent-guides]
render = true
character = "┆" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 0

[editor.statusline]
# separator = "§" # 00A7: section
# separator = "‡" # 2021: double dagger
# separator = "•" # 2022: bullet
# separator = "□" # 25A1: square
# separator = "…" # 2026: ellipsis
# separator = "␣" # 2423: space symbol
# separator = "∞" # 221E: infinity
# separator = "×" # 00D7: multiplication sign
# separator = "≈" # 2248: almost equal to
# separator = "≡" # 2261: equiv, Congruent, equivalent to
separator = "∎" # 220E: End of proof
# separator = "○" # 25CB: circle
left = [
  "mode",
  "spinner",
  "separator",
  "selections",
  "primary-selection-length",
  "register",
  "separator",
  "total-line-numbers",
  "position",
  "position-percentage",
]
center = [
  "file-modification-indicator",
  "spacer",
  "version-control",
  "spacer",
  "separator",
  "read-only-indicator",
  "separator",
  "file-name",
  "separator",
  "read-only-indicator",
  "separator",
  "spacer",
  "version-control",
  "spacer",
  "file-modification-indicator",
]
right = [
  "diagnostics",
  "workspace-diagnostics",
  "separator",
  "file-type",
  "file-indent-style",
  "separator",
  "file-encoding",
  "file-line-ending",
]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[editor.search]
smart-case = true
wrap-around = true

[editor.file-picker]
hidden = false
follow-symlinks = true
deduplicate-links = true
parents = true
ignore = true
git-ignore = true
git-global = true
git-exclude = true

[editor.lsp]
enable = true
display-messages = true
display-progress-messages = true
display-color-swatches = true
display-signature-help-docs = true
auto-signature-help = false
display-inlay-hints = true
# inlay-hints-length-limit = ?
snippets = true
goto-reference-include-declaration = true

[editor.inline-diagnostics]
# The minimum severity that a diagnostic must have to be shown inline on
# the line that contains the primary cursor. Set to disable to not show any
# diagnostics inline. This option does not have any effect when in insert-mode
# and will only take effect 350ms after moving the cursor to a different line.
cursor-line = "warning"
# The minimum severity that a diagnostic must have to be shown inline on a
# line that does not contain the cursor-line. Set to disable to not show any
# diagnostics inline.
# Enabling this makes it so that insert mode doesn't hide inline diagnostics
other-lines = "disable"

[keys.normal]
C-v = "paste_before"
C-S-v = "paste_clipboard_before"
C-s = ":write"
"C-/" = "toggle_comments"
# Same as <C-/> but for compatability with some terminals that are not configured properly or are unconfigurable
C-7 = "toggle_comments"
C-q = ":buffer-close"
# So that the extensions respects the direction of the selection head/anchor
x = "extend_line"
V = ["goto_first_nonwhitespace", "extend_to_line_end"]
C-end = "goto_file_end"
home = "goto_first_nonwhitespace"
A-home = "goto_line_start"
C-home = "goto_file_start"
C-space = "signature_help"
C-left = ["move_prev_word_start", "collapse_selection"]
C-right = ["move_next_word_start", "collapse_selection"]
C-down = "page_cursor_half_down"
C-up = "page_cursor_half_up"
# a = ["append_mode", "collapse_selection"]
# i = ["insert_mode", "collapse_selection"]
S-left = "extend_char_left"
S-right = "extend_char_right"
S-up = "extend_visual_line_up"
S-down = "extend_visual_line_down"
"C-p" = ':lsp-workspace-command tinymist.pinMain "%sh{realpath %{buffer_name}}"'

[keys.normal.g]
e = "goto_file_end"

[keys.normal.space]
"=" = ":format"
H = ":toggle-option lsp.display-inlay-hints"

[keys.normal.space.q.w]
ret = ":quit"
c = ":quit"
a = ":quit-all"

[keys.normal.space.q.w.C]
ret = ":quit"
"!" = ":quit!"
w.ret = ":write-quit"
w."!" = ":write-quit!"

[keys.normal.space.q.w.A]
ret = ":quit-all"
"!" = ":quit-all!"
w.ret = ":write-quit-all"
w."!" = ":write-quit-all!"

[keys.normal.space.q.b]
ret = ":buffer-close"
c = ":buffer-close"
a = ":buffer-close-all"
o = ":buffer-close-others"
v = ":buffer-close-others --skip-visible"

[keys.normal.space.q.b.C]
ret = ":buffer-close"
"!" = ":buffer-close!"
w.ret = ":write-buffer-close"
w."!" = ":write-buffer-close!"
w.f.ret = ":write-buffer-close --no-format"
w.f."!" = ":write-buffer-close! --no-format"

[keys.normal.space.q.b.A]
ret = ":buffer-close-all"
"!" = ":buffer-close-all!"
w.ret = [":write-all", ":buffer-close-all"]
w."!" = [":write-all!", ":buffer-close-all!"]
w.f.ret = [":write-all --no-format", ":buffer-close-all"]
w.f."!" = [":write-all! --no-format", ":buffer-close-all!"]

[keys.normal.space.q.b.O]
ret = ":buffer-close-others"
"!" = ":buffer-close-others!"

[keys.normal.space.q.b.V]
ret = ":buffer-close-others --skip-visible"
"!" = ":buffer-close-others! --skip-visible"


[keys.select]
";" = ["collapse_selection", "normal_mode"]
C-s = ":write"
"C-/" = "toggle_comments"
# Same as <C-/> but for compatability with some terminals that are not configured properly or are unconfigurable
C-7 = "toggle_comments"
# So that the extensions respects the direction of the selection head/anchor
x = "extend_line"
C-left = "extend_prev_word_start"
C-right = "extend_next_word_start"
C-down = "page_cursor_half_down"
C-up = "page_cursor_half_up"
S-left = "extend_char_left"
S-right = "extend_char_right"
S-up = "extend_visual_line_up"
S-down = "extend_visual_line_down"

[keys.select.space]
"=" = ":format"
H = ":toggle-option lsp.display-inlay-hints"

[keys.select.space.q.w]
ret = ":quit"
c = ":quit"
a = ":quit-all"

[keys.select.space.q.w.C]
ret = ":quit"
"!" = ":quit!"
w.ret = ":write-quit"
w."!" = ":write-quit!"

[keys.select.space.q.w.A]
ret = ":quit-all"
"!" = ":quit-all!"
w.ret = ":write-quit-all"
w."!" = ":write-quit-all!"

[keys.select.space.q.b]
ret = ":buffer-close"
c = ":buffer-close"
a = ":buffer-close-all"
o = ":buffer-close-others"
v = ":buffer-close-others --skip-visible"

[keys.select.space.q.b.C]
ret = ":buffer-close"
"!" = ":buffer-close!"
w.ret = ":write-buffer-close"
w."!" = ":write-buffer-close!"
w.f.ret = ":write-buffer-close --no-format"
w.f."!" = ":write-buffer-close! --no-format"

[keys.select.space.q.b.A]
ret = ":buffer-close-all"
"!" = ":buffer-close-all!"
w.ret = [":write-all", ":buffer-close-all"]
w."!" = [":write-all!", ":buffer-close-all!"]
w.f.ret = [":write-all --no-format", ":buffer-close-all"]
w.f."!" = [":write-all! --no-format", ":buffer-close-all!"]

[keys.select.space.q.b.O]
ret = ":buffer-close-others"
"!" = ":buffer-close-others!"

[keys.select.space.q.b.V]
ret = ":buffer-close-others --skip-visible"
"!" = ":buffer-close-others! --skip-visible"

[keys.insert]
C-s = ":write"
"C-/" = "toggle_comments"
# Same as <C-/> but for compatability with some terminals that are not configured properly or are unconfigurable
C-7 = "toggle_comments"
C-z = "undo"
C-A-z = "redo"
C-v = "paste_clipboard_before"
C-S-v = "paste_clipboard_before"
C-p = "paste_before"
C-A-p = "paste_clipboard_before"
C-end = "goto_file_end"
home = "goto_first_nonwhitespace"
A-home = "goto_line_start"
C-home = "goto_file_start"
C-space = "signature_help"
C-c = "toggle_comments"
C-left = ["move_prev_word_start", "collapse_selection"]
C-right = ["move_next_word_start", "collapse_selection"]
# C-e = "normal_mode" # Can use `C-[` since that is the `esc` keycode
# j = { k = "normal_mode" } # Maps `jk` to exit insert mode

# [keys.insert."C-p"]
# # P = "paste_clipboard_before"
# C-P = "paste_clipboard_before"
# # p = "paste_before"
# C-p = "paste_before"
